export const LLM_PRIMARY_PROVIDER = 'LLM_PRIMARY_PROVIDER';
export const LLM_PRIMARY_CONFIG = 'LLM_PRIMARY_CONFIG';
export const LLM_FALLBACK_PROVIDER = 'LLM_FALLBACK_PROVIDER';
export const LLM_FALLBACK_CONFIG = 'LLM_FALLBACK_CONFIG';
